version: '3'

networks:
  wss-site_app-network:
    external: true

services:
  frontend:
    image: wss6:frontend
    container_name: frontend6
    ports:
      - 3006:3000
    networks:
      - wss-site_app-network
    env_file:
      - .env