version: '3'

networks:
  app-net:
    external: true
    name: app

services:
  frontend6:
    image: wss:front6
    container_name: frontend6
    ports:
      - 3006:3000
    networks:
      - app-net
    env_file:
      - .env
