version: '3'

networks:
  app-net:
    external: true
    name: app

services:
  frontend8:
    image: wss:front8
    container_name: frontend8
    ports:
      - 3008:3000
    networks:
      - app-net
    env_file:
      - .env
