version: '3'

networks:
  wss-site_app-network:
    external: true

services:
  frontend:
    image: wss5:frontend
    container_name: frontend5
    ports:
      - 3005:3000
    networks:
      - wss-site_app-network
    env_file:
      - .env