version: '3'

networks:
  app-net:
    external: true
    name: app

services:
  frontend5:
    image: wss:front5
    container_name: frontend5
    ports:
      - 3005:3000
    networks:
      - app-net
    env_file:
      - .env
