version: '3'

networks:
  wss-site_app-network:
    external: true

services:
  frontend:
    image: wss7:frontend
    container_name: frontend7
    ports:
      - 3007:3000
    networks:
      - wss-site_app-network
    env_file:
      - .env