version: '3'

networks:
  app-net:
    external: true
    name: app

services:
  frontend7:
    image: wss:front7
    container_name: frontend7
    ports:
      - 3007:3000
    networks:
      - app-net
    env_file:
      - .env
