version: '3'

networks:
  wss-site_app-network:
    external: true

services:
  frontend:
    image: wss9:frontend
    container_name: frontend9
    ports:
      - 3009:3000
    networks:
      - wss-site_app-network
    env_file:
      - .env.frontend