version: '3'

networks:
  app-net:
    external: true
    name: app

services:
  frontend3:
    image: wss:front3
    container_name: frontend3
    ports:
      - 3003:3000
    networks:
      - app-net
    env_file:
      - .env
