version: '3'

networks:
  app-net:
    external: true
    name: app

services:
  frontend4:
    image: wss:front4
    container_name: frontend4
    ports:
      - 3004:3000
    networks:
      - app-net
    env_file:
      - .env
