version: '3'

networks:
  wss-site_app-network:
    external: true

services:
  frontend:
    image: wss4:frontend
    container_name: frontend4
    ports:
      - 3004:3000
    networks:
      - wss-site_app-network
    env_file:
      - .env